### ISSUE TITLE
QLabeledRangeSlider does not support methods using the bar

### ISSUE THREAD

**Issue by TheZappie** [tlambert03/QtRangeSlider#19]
QLabeledRangeSlider does not seem to support methods using the bar, while there is a bar present. Feature request: support bar methods such as setBarIsVisible, setBarMovesAllHandles and setBarIsRigid. 

Code:
a = QLabeledRangeSlider()
a.hideBar()
Traceback (most recent call last):
  File "<ipython-input-31-d098035c57f9>", line 1, in <module>
    a.hideBar()
AttributeError: 'QLabeledRangeSlider' object has no attribute 'hideBar'

Amazing package by the way!

**Comment by tlambert03** [comment]
Thanks!  Yeah, the labeled variants are not behaving as good wrappers.  Thank you for the bug report. 

As a temporary workaround, you can access the "actual" range slider at `a._slider` (in your example).  Shouldn't have to do that... but until I fix it.

**Comment by tlambert03** [comment]
hi @OMGSuperZappie ... the content of this package is moving to [superqt](https://github.com/napari/superqt)... so I'm moving this issue [there](https://github.com/napari/superqt/issues/4)
